language: python

sudo: false

env:
  - LUA="lua=5.1"

before_install:
  - pip install hererocks
  - hererocks base -r^ --$LUA
  - export PATH=$PATH:$PWD/base/bin # Add directory with all installed binaries to PATH
  - luarocks install busted
  - luarocks install luacov-coveralls

script: busted test
after_script:
  - busted -c test
  - luacov-coveralls
